name: CI
on:
  push: 
  pull_request:
  workflow_dispatch:

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip3 install homeassistant
      - run: pip3 install ruff
      - run: ruff check
      - run: ruff format